### ISSUE TITLE
JustWatch Class can not be instantiated raises typeError 

### ISSUE THREAD

**Issue by ashgazer** [dawoudt/JustWatchAPI#47]
This has something to do with when trying to set the country
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
, in __init__
    self.locale = self.set_locale()
, in set_locale
    if result['iso_3166_2'] == self.country or \
TypeError: string indices must be integers
`

**Comment by venkibale** [comment]
Facing similar issue, any help would be appreciated! @ashgazer  any resolution on this?

**Comment by drexeljoe** [comment]
Same experience here. First noticed on Sep 9. The behavior is the same whether a country value is provided or not.

`>>> just_watch = JustWatch()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/justwatch/justwatchapi.py", line 18, in __init__
    self.locale = self.set_locale()
  File "/usr/local/lib/python3.7/site-packages/justwatch/justwatchapi.py", line 45, in set_locale
    if result['iso_3166_2'] == self.country or \
TypeError: string indices must be integers
`

`>>> just_watch = JustWatch(country='US')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/justwatch/justwatchapi.py", line 18, in __init__
    self.locale = self.set_locale()
  File "/usr/local/lib/python3.7/site-packages/justwatch/justwatchapi.py", line 45, in set_locale
    if result['iso_3166_2'] == self.country or \
TypeError: string indices must be integers
`

**Comment by venkibale** [comment]
Justwatch site is still functioning, is it like public use is restricted now?

**Comment by dreondre** [comment]
> Justwatch site is still functioning, is it like public use is restricted now?

It's entirely possible. When I first found this repository, JW didn't have this page and now they do. 
https://www.justwatch.com/ca/JustWatch-Streaming-API

**Comment by venkibale** [comment]
Ohh, could be. I didn't find any good alternative as well.

**Comment by chkuendig** [comment]
Looks like an intentional change from their side. 

` curl "https://apis.justwatch.com/content/locales/state" ` or opening the url in the browser works just fine
`curl "https://apis.justwatch.com/content/locales/state" --user-agent 'JustWatch Python client (github.com/dawoudt/JustWatchAPI)'` only returns a empty object

**Comment by rking32** [comment]
thanks for @chkuendig's [idea](https://github.com/dawoudt/JustWatchAPI/issues/47#issuecomment-691357371) 
using that i made a temp solution. but its not best.
```python
from justwatch import JustWatch, justwatchapi

justwatchapi.__dict__['HEADER'] = {
    'User-Agent': 'JustWatch client (github.com/dawoudt/JustWatchAPI)'}

just_watch = JustWatch()
```

**Comment by ashgazer** [comment]
@venkibale @rking32 I created a pull request for changing the user agent. Hopefully this gets merged soon.

https://github.com/dawoudt/JustWatchAPI/pull/48
